language: node_js
node_js:
- '0.12'
before_deploy:
- npm run build
deploy:
  provider: s3
  skip_cleanup: true
  access_key_id: AKIAIF5X3OAI5OORPVKQ
  bucket: www.ve3ta.com
  local-dir: site
  region: us-west-2
  on:
    branch: master
    repo: k88hudson/ve3ta
  secret_access_key:
    secure: IOK+PSJlaNH3Ytj2aVvGxRP6zLiPAu4UU1pHtxfZdHkeKGA2kseGEIV6GxtW3lP+Fu/WINfhp8674IgHLlI4hJe4KgFA3Iujego3ASbVX/foCi7nvu7+oH3C8fEChp151p0kt/q1BPtSVUOrv1rlC1FHSrfoYjWkQaXpK6KSvmA=
